[meta]
firstName = "Kayvan"
lastName = "Shah"
role = "Data Engineer"
about = """A passionate learner | ML/AI enthusiast"""

[meta.location]
city = "Mumbai"
country = "India"
logo = "https://www.flaticon.com/svg/static/icons/svg/330/330176.svg"

[[social]]
name = "github"
url = "https://github.com/KayvanShah1"
logo = "https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white"

[[social]]
name = "gitlab"
url = "https://gitlab.com/kayvanshah1"
logo = "https://img.shields.io/badge/GitLab-330F63?style=for-the-badge&logo=gitlab&logoColor=white"

[[social]]
name = "linkedin"
url = "https://www.linkedin.com/in/kayvanshah999/"
logo = "https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white"

[[social]]
name = "kaggle"
url = "https://www.kaggle.com/kayvanshah"
logo = "https://img.shields.io/badge/Kaggle-20BEFF?style=for-the-badge&logo=Kaggle&logoColor=whitee"

[technologies]
python = "https://img.shields.io/badge/Python-black?logo=python&amp;style=plastic"   
numpy = "https://img.shields.io/badge/NumPy-black?logo=numpy&amp;style=plastic" 
pandas = "https://img.shields.io/badge/Pandas-black?logo=pandas&amp;style=plastic"
plotly = "https://img.shields.io/badge/Plotly-black?logo=plotly&amp;style=plastic"
folium = "https://img.shields.io/badge/Folium-black?logo=folium&amp;style=plastic"
scikit-learn = "https://img.shields.io/badge/Scikit%20Learn-black?logo=scikit-learn&amp;style=plastic" 
tensorflow = "https://img.shields.io/badge/Tensorflow-black?logo=tensorflow&amp;style=plastic"
opencv = "https://img.shields.io/badge/OpenCV-black?logo=opencv&amp;style=plastic"
pytorch = "https://img.shields.io/badge/Pytorch-black?logo=pytorch&amp;style=plastic" 
fastapi = "https://img.shields.io/badge/FastAPI-black?logo=fastapi&amp;style=plastic"
selenium = "https://img.shields.io/badge/Selenium-black?logo=selenium&amp;style=plastic" 
django = "https://img.shields.io/badge/Django-black?logo=django&amp;style=plastic" 
html5 = "https://img.shields.io/badge/HTML5-black?logo=html5&amp;style=plastic"
css3 = "https://img.shields.io/badge/CSS3-black?logo=css3&amp;style=plastic"
javascript = "https://img.shields.io/badge/JavaScript-black?logo=javascript&amp;style=plastic"
mysql = "https://img.shields.io/badge/MySQL-black?logo=mysql&amp;style=plastic"
postgresql = "https://img.shields.io/badge/PostgreSQL-black?logo=postgresql&amp;style=plastic"
mongodb = "https://img.shields.io/badge/MongoDB-black?logo=mongodb&amp;style=plastic"
elasticsearch = "https://img.shields.io/badge/Elasticsearch-black?logo=elasticsearch&amp;style=plastic"
kibana = "https://img.shields.io/badge/Kibana-black?logo=kibana&amp;style=plastic"
vscode = "https://img.shields.io/badge/VSCode-black?logo=visual-studio-code&amp;style=plastic" 
chrome = "https://img.shields.io/badge/Google%20Chrome-black?logo=google-chrome&amp;style=plastic" 
brave = "https://img.shields.io/badge/Brave-black?logo=brave&amp;style=plastic" 
git = "https://img.shields.io/badge/Git-black?logo=git&amp;style=plastic" 
docker = "https://img.shields.io/badge/Docker-black?logo=docker&amp;style=plastic" 
kubernetes = "https://img.shields.io/badge/Kubernetes-black?logo=kubernetes&amp;style=plastic"
terraform = "https://img.shields.io/badge/Terraform-black?logo=terraform&amp;style=plastic"
github-actions = "https://img.shields.io/badge/Github%20Actions-black?logo=github-actions&amp;style=plastic" 
google-cloud-platform = "https://img.shields.io/badge/GCP-black?logo=google-cloud&amp;style=plastic" 
amazon-aws = "https://img.shields.io/badge/AWS-black?logo=amazon-aws&amp;style=plastic" 
heroku = "https://img.shields.io/badge/Heroku-black?logo=heroku&amp;style=plastic" 
jupyter = "https://img.shields.io/badge/Jupyter Notebook-black?logo=jupyter&amp;style=plastic"
googlecolab = "https://img.shields.io/badge/Google Colab-black?logo=googlecolab&amp;style=plastic"